## defaults for _all_ profiles
[profile.default]
src = "src"
out = "out"
script = "script"
test = "test"
libs = ["lib"]
solc = "0.8.10" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
